/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package suSatis;

import javax.swing.JOptionPane;

/**
 *
 * @author ilayda
 */
public class MusteriDuzenle extends javax.swing.JFrame {

    /**
     * Creates new form MusteriDuzenle
     */
    public MusteriDuzenle() {
        super("Müsteri Düzenle");
        initComponents();
        pack();
    }
    
    int id;
    public void musteriId(int musteriId){
        id=musteriId;
    }
    
   public MusteriDuzenle(String adi, String soyadi, String telefon, String adres){
       initComponents();
       m_upd_adi.setText(adi);
       m_upd_soyadi.setText(soyadi);
       m_upd_telefon.setText(telefon);
       m_upd_adres.setText(adres);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        m_upd_adres = new javax.swing.JTextField();
        m_upd_telefon = new javax.swing.JTextField();
        m_upd_soyadi = new javax.swing.JTextField();
        m_upd_adi = new javax.swing.JTextField();
        musteriDuzenle = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 506));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Adı :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 160, 31, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Soyadı :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 220, 55, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Telefon :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 280, 60, 17);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Adres :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 340, 70, 17);

        m_upd_adres.setPreferredSize(new java.awt.Dimension(6, 23));
        m_upd_adres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_upd_adresActionPerformed(evt);
            }
        });
        getContentPane().add(m_upd_adres);
        m_upd_adres.setBounds(240, 330, 390, 30);

        m_upd_telefon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(m_upd_telefon);
        m_upd_telefon.setBounds(240, 270, 388, 30);

        m_upd_soyadi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(m_upd_soyadi);
        m_upd_soyadi.setBounds(240, 210, 388, 30);

        m_upd_adi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(m_upd_adi);
        m_upd_adi.setBounds(240, 150, 388, 30);

        musteriDuzenle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/done.png"))); // NOI18N
        musteriDuzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriDuzenleActionPerformed(evt);
            }
        });
        getContentPane().add(musteriDuzenle);
        musteriDuzenle.setBounds(370, 370, 81, 57);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arkaPlan/markaplan.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMaximumSize(new java.awt.Dimension(900, 506));
        jLabel5.setMinimumSize(new java.awt.Dimension(900, 506));
        jLabel5.setPreferredSize(new java.awt.Dimension(900, 506));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 900, 500);

        setBounds(0, 0, 900, 506);
    }// </editor-fold>//GEN-END:initComponents

    private void m_upd_adresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_upd_adresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_upd_adresActionPerformed

    private void musteriDuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriDuzenleActionPerformed
        // TODO add your handling code here:
        

        if (id > 0) {
            String adi = m_upd_adi.getText().trim();
            String soyadi = m_upd_soyadi.getText().trim();
            String telefon = m_upd_telefon.getText().trim();
            String adres = m_upd_adres.getText().trim();
            
            if (adi.equals("")||soyadi.equals("")||telefon.equals("")||adres.equals("")) {
                
                JOptionPane.showMessageDialog(rootPane, "Lütfen tüm alanları doldurunuz");
                m_upd_adi.requestFocus(); 
            }else{
        
                DB db = new DB();
                int status = db.musteriUpdate(adi, soyadi, telefon, adres, id);
                db.close();
                if (status > 0) {
                m_upd_adi.setText("");
                m_upd_soyadi.setText("");
                m_upd_telefon.setText("");
                m_upd_adres.setText("");
                m_upd_adi.requestFocus();
                Siparis siparis =new Siparis();
                siparis.setVisible(true);
                dispose();
                               
                }if (status == - 1) {
                JOptionPane.showMessageDialog(rootPane, "Bu telefon daha önce eklenmiş");              
            }
            }
            id=0;      
        }else{
            JOptionPane.showMessageDialog(rootPane, "Lütfen tüm alanları doldurunuz");
        }
    }//GEN-LAST:event_musteriDuzenleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriDuzenle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriDuzenle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriDuzenle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriDuzenle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriDuzenle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField m_upd_adi;
    private javax.swing.JTextField m_upd_adres;
    private javax.swing.JTextField m_upd_soyadi;
    private javax.swing.JTextField m_upd_telefon;
    private javax.swing.JButton musteriDuzenle;
    // End of variables declaration//GEN-END:variables
}
