/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package suSatis;

import javax.swing.JOptionPane;
import suSatis.Siparis;

public class MusteriKayit extends javax.swing.JFrame {

    public MusteriKayit() {
        super("Müsteri Kayit");
        initComponents();
        pack();
    }
    
    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        m_kyt_adi = new javax.swing.JTextField();
        m_kyt_soyadi = new javax.swing.JTextField();
        m_kyt_telefon = new javax.swing.JTextField();
        musteriKayit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        m_kyt_adres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arkaPlan/markaplan.png"))); // NOI18N
        jLabel5.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 506));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Adres :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 330, 70, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Soyadı :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 210, 55, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Telefon :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 270, 60, 17);

        m_kyt_adi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(m_kyt_adi);
        m_kyt_adi.setBounds(240, 140, 388, 30);

        m_kyt_soyadi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(m_kyt_soyadi);
        m_kyt_soyadi.setBounds(240, 200, 388, 30);

        m_kyt_telefon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(m_kyt_telefon);
        m_kyt_telefon.setBounds(240, 260, 388, 30);

        musteriKayit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/done.png"))); // NOI18N
        musteriKayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriKayitActionPerformed(evt);
            }
        });
        getContentPane().add(musteriKayit);
        musteriKayit.setBounds(370, 370, 81, 57);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Adı :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 150, 31, 17);

        m_kyt_adres.setPreferredSize(new java.awt.Dimension(6, 23));
        m_kyt_adres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_kyt_adresActionPerformed(evt);
            }
        });
        getContentPane().add(m_kyt_adres);
        m_kyt_adres.setBounds(240, 320, 390, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arkaPlan/markaplan.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 900, 510);

        setSize(new java.awt.Dimension(900, 506));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void m_kyt_adresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_kyt_adresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_kyt_adresActionPerformed

    private void musteriKayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriKayitActionPerformed
        // TODO add your handling code here:
        String adi = m_kyt_adi.getText().trim();
        String soyadi = m_kyt_soyadi.getText().trim();
        String telefon = m_kyt_telefon.getText().trim();
        String adres = m_kyt_adres.getText().trim();
   
        
      
        if(adi.equals("")|| soyadi.equals("")||telefon.equals("") ||adres.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Lütfen tüm alanları doldurunuz");
            m_kyt_adi.requestFocus();       
        }
        else{
            DB db = new DB();
            int status = db.musteriInsert(adi, soyadi, telefon, adres);
            db.close();
            if (status > 0) {
                m_kyt_adi.setText("");
                m_kyt_soyadi.setText("");
                m_kyt_telefon.setText("");
                m_kyt_adres.setText("");
                m_kyt_adi.requestFocus();
                
             
            }
            if (status == - 1) {
                JOptionPane.showMessageDialog(rootPane, "Bu telefon daha önce eklenmiş");              
            }else{
                Siparis siparis=new Siparis();
                siparis.setVisible(true);
                dispose(); //kapar sayfayı 
            }
        }
    }//GEN-LAST:event_musteriKayitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriKayit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField m_kyt_adi;
    private javax.swing.JTextField m_kyt_adres;
    private javax.swing.JTextField m_kyt_soyadi;
    private javax.swing.JTextField m_kyt_telefon;
    private javax.swing.JButton musteriKayit;
    // End of variables declaration//GEN-END:variables
}
