/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package suSatis;

import javax.swing.JOptionPane;

/**
 *
 * @author ilayda
 */
public class SiparisKayit extends javax.swing.JFrame {

    /**
     * Creates new form SiparisKayit
     */
    public SiparisKayit() {
        super("Siparis Kayit");
        initComponents();
        pack();
    }

    public  SiparisKayit(String adi, String soyadi, String adres) {
        initComponents();
        s_kyt_adi.setText(adi);
        s_kyt_soyadi.setText(soyadi);
        s_kyt_adres.setText(adres);
        
    }
    
    

    //SiparisKayit(String adi, String soyadi, String adres) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        siparisKayit = new javax.swing.JButton();
        s_kyt_soyadi = new javax.swing.JTextField();
        s_kyt_adres = new javax.swing.JTextField();
        s_kyt_adi = new javax.swing.JTextField();
        s_kyt_tutar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Adı :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 170, 31, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Soyadı :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 220, 60, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Adres :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 270, 50, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tutar :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 320, 47, 17);

        siparisKayit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/done.png"))); // NOI18N
        siparisKayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siparisKayitActionPerformed(evt);
            }
        });
        getContentPane().add(siparisKayit);
        siparisKayit.setBounds(420, 350, 80, 50);
        getContentPane().add(s_kyt_soyadi);
        s_kyt_soyadi.setBounds(280, 210, 390, 30);
        getContentPane().add(s_kyt_adres);
        s_kyt_adres.setBounds(280, 260, 390, 30);
        getContentPane().add(s_kyt_adi);
        s_kyt_adi.setBounds(280, 160, 390, 30);
        getContentPane().add(s_kyt_tutar);
        s_kyt_tutar.setBounds(280, 310, 390, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arkaPlan/markaplan.png"))); // NOI18N
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 900, 500);

        setSize(new java.awt.Dimension(900, 506));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    private void siparisKayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siparisKayitActionPerformed
        // TODO add your handling code here:
        
        
            String adi =s_kyt_adi.getText().trim();
            String soyadi = s_kyt_soyadi.getText().trim();
            String adres = s_kyt_adres.getText().trim();
            String tutar = s_kyt_tutar.getText().trim();
            
            if (adi.equals("")||soyadi.equals("")||adres.equals("")||tutar.equals("")) {
                
                JOptionPane.showMessageDialog(rootPane, "Lütfen tüm alanları doldurunuz");
                s_kyt_adi.requestFocus(); 
            }else{
        
                DB db = new DB();
                int status = db.siparisInsert(adi, soyadi, adres,tutar);
                db.close();
                if (status > 0) {
                s_kyt_adi.setText("");
                s_kyt_soyadi.setText("");
                s_kyt_adres.setText("");
                s_kyt_tutar.setText("");
                s_kyt_adi.requestFocus();
                Siparis siparis =new Siparis();
                siparis.setVisible(true);
                dispose();
                               
                }
                 
        }
    }//GEN-LAST:event_siparisKayitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiparisKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiparisKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiparisKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiparisKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiparisKayit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField s_kyt_adi;
    private javax.swing.JTextField s_kyt_adres;
    private javax.swing.JTextField s_kyt_soyadi;
    private javax.swing.JTextField s_kyt_tutar;
    private javax.swing.JButton siparisKayit;
    // End of variables declaration//GEN-END:variables
}
