/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package suSatis;

import java.sql.DatabaseMetaData;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ilayda
 */
public class Siparis extends javax.swing.JFrame {

    /**
     * Creates new form müster
     */
    public Siparis() {
        super("Siparis");
        initComponents();
        refreshMusteri();
        refreshSiparis();
        
        pack();

    }
    private void refreshMusteri(){
        DB db = new DB();
        tbl_musteri.setModel(db.allMusteri());
        db.close();
    }
       private void refreshSiparis(){
        DB db = new DB();
        tbl_siparis.setModel(db.allSiparis());
        db.close();
    }

   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        arama = new javax.swing.JButton();
        madi = new javax.swing.JTextField();
        msoyadi = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        s_sil = new javax.swing.JButton();
        t_sil = new javax.swing.JButton();
        bsiparis = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_musteri = new javax.swing.JTable();
        yeniMüsteri = new javax.swing.JButton();
        duzenle = new javax.swing.JButton();
        sil = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_siparis = new javax.swing.JTable();
        ySipariş = new javax.swing.JButton();
        yolda = new javax.swing.JButton();
        teslimedildi = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 665));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Arama", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel9.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Müşteri Adı :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Müşteri Soyadı :");

        arama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ara.png"))); // NOI18N
        arama.setText("Ara");
        arama.setActionCommand("");
        arama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aramaActionPerformed(evt);
            }
        });

        madi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(msoyadi, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(madi, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(arama)
                .addGap(26, 26, 26))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(madi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(msoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(arama))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel9);
        jPanel9.setBounds(10, 40, 480, 125);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tablo İşlemleri", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel11.setOpaque(false);

        s_sil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        s_sil.setText("Seçili Olanı Sil");
        s_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_silActionPerformed(evt);
            }
        });

        t_sil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_sil.setText("Tümünü Sil");
        t_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_silActionPerformed(evt);
            }
        });

        bsiparis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bsiparis.setText("Bugünün Siparişleri");
        bsiparis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsiparisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(s_sil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(t_sil)
                .addGap(34, 34, 34)
                .addComponent(bsiparis)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_sil)
                    .addComponent(t_sil)
                    .addComponent(bsiparis))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel11);
        jPanel11.setBounds(510, 40, 480, 120);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Müşteriler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel12.setOpaque(false);

        jScrollPane1.setOpaque(false);

        tbl_musteri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_musteri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_musteriMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_musteri);

        yeniMüsteri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/yeni_musteri.png"))); // NOI18N
        yeniMüsteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yeniMüsteriActionPerformed(evt);
            }
        });

        duzenle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        duzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duzenleActionPerformed(evt);
            }
        });

        sil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sil.png"))); // NOI18N
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(yeniMüsteri, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(duzenle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(sil)
                .addGap(59, 59, 59))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(duzenle, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sil, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(yeniMüsteri, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel12);
        jPanel12.setBounds(10, 180, 480, 410);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Siparişler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel13.setOpaque(false);

        tbl_siparis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_siparis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_siparisMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_siparis);

        ySipariş.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/yeni_siparis.png"))); // NOI18N
        ySipariş.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ySiparişActionPerformed(evt);
            }
        });

        yolda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/yold.png"))); // NOI18N
        yolda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoldaActionPerformed(evt);
            }
        });

        teslimedildi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/teslim edildi.png"))); // NOI18N
        teslimedildi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teslimedildiActionPerformed(evt);
            }
        });

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refresh))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(ySipariş)
                        .addGap(33, 33, 33)
                        .addComponent(yolda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(teslimedildi)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(refresh)
                .addGap(38, 38, 38)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ySipariş)
                    .addComponent(yolda, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teslimedildi))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel13);
        jPanel13.setBounds(510, 180, 480, 410);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arkaPlan/siparis_aplan.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1000, 665);

        setSize(new java.awt.Dimension(1017, 706));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aramaActionPerformed
        // TODO add your handling code here:
        String adi= madi.getText().trim();
        String soyadi = msoyadi.getText().trim();
        if (adi.equals("")|| soyadi.equals("")) {
            
            JOptionPane.showMessageDialog(rootPane, "Müşteri adı ve soyadı boş olamaz");
        }else {
            DB db = new DB();
            tbl_musteri.setModel(db.musteriSearch(adi,soyadi));
            db.close();
            
        }
        

        
    }//GEN-LAST:event_aramaActionPerformed


    private void madiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_madiActionPerformed

    private void yeniMüsteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yeniMüsteriActionPerformed
        // TODO add your handling code here:
        MusteriKayit musteriKayit=new MusteriKayit();
        musteriKayit.setVisible(true);
        dispose();
    }//GEN-LAST:event_yeniMüsteriActionPerformed
    
    private void duzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duzenleActionPerformed
        // TODO add your handling code here:
        if(id>0){
            
            musteriDuzenle.setVisible(true);
            musteriDuzenle.musteriId(id);
            dispose();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Lütfen seçim yapınız");
        }
        
        
    }//GEN-LAST:event_duzenleActionPerformed
    int id=0;
    MusteriDuzenle musteriDuzenle;
    SiparisKayit siparisKayit;
    private void tbl_musteriMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_musteriMouseReleased
        // TODO add your handling code here:
        int row = tbl_musteri.getSelectedRow();
        
        id=(int) tbl_musteri.getValueAt(row,0);
        String adi = (String) tbl_musteri.getValueAt(row, 1);
        String soyadi = (String) tbl_musteri.getValueAt(row, 2);
        String telefon = (String) tbl_musteri.getValueAt(row, 3);
        String adres = (String) tbl_musteri.getValueAt(row, 4);
        
        musteriDuzenle = new MusteriDuzenle(adi,soyadi,telefon,adres);
       siparisKayit = new SiparisKayit(adi,soyadi, adres);
    }//GEN-LAST:event_tbl_musteriMouseReleased

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        // TODO add your handling code here:
            if (id>0) {
            int select=JOptionPane.showConfirmDialog(rootPane, "Silmek istedğinizden emin misniz?", "Silme İşlemi", JOptionPane.YES_NO_OPTION);
            if(select == 0){
                DB db =new  DB();
                int status = db.musteriDelete(id);
                db.close();
                if (status >0){
                    refreshMusteri();
                
                }
            id=0;
            }              
        }else{
            JOptionPane.showMessageDialog(rootPane, "Lütfen seçim yapınız");
        }
    }//GEN-LAST:event_silActionPerformed
   
    private void ySiparişActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ySiparişActionPerformed
        
        // TODO add your handling code here:
        
        if(id>0){
          
            siparisKayit.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Lütfen seçim yapınız");
        }
        
        
    }//GEN-LAST:event_ySiparişActionPerformed
    int siparisId=0;
    private void tbl_siparisMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_siparisMouseReleased
        // TODO add your handling code here:
        int row = tbl_siparis.getSelectedRow();
        siparisId= (int) tbl_siparis.getValueAt(row,0);
        String sadi = (String) tbl_siparis.getValueAt(row, 1);
        String ssoyadi = (String) tbl_siparis.getValueAt(row, 2);
        String sdurum = (String) tbl_siparis.getValueAt(row, 3);
        String sadres = (String) tbl_siparis.getValueAt(row, 4);
        String stutar = (String) tbl_siparis.getValueAt(row, 5);
        
        
        
        
    }//GEN-LAST:event_tbl_siparisMouseReleased

    private void yoldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoldaActionPerformed
        // TODO add your handling code here:
        if(siparisId>0){
            DB db= new DB();
            int status = db.siparisYolaCikti(siparisId);
            db.close();
            refreshSiparis();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Lütfen seçim yapınız.");
        }
    }//GEN-LAST:event_yoldaActionPerformed

    private void teslimedildiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teslimedildiActionPerformed
        // TODO add your handling code here:
        if(siparisId>0){
            DB db= new DB();
            int status = db.siparisTeslimEdildi(siparisId);
            db.close();
            refreshSiparis();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Lütfen seçim yapınız.");
        }
    }//GEN-LAST:event_teslimedildiActionPerformed
    
    private void s_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_silActionPerformed
        // TODO add your handling code here:
        if (siparisId>0) {
            int select=JOptionPane.showConfirmDialog(rootPane, "Silmek istedğinizden emin misniz?", "Silme İşlemi", JOptionPane.YES_NO_OPTION);
            if(select == 0){
                DB db =new  DB();
                int status = db.siparisDelete(siparisId);
                db.close();
                if (status >0){
                    refreshSiparis();
                
                }
            siparisId=0;
            }              
        }else{
            JOptionPane.showMessageDialog(rootPane, "Lütfen seçim yapınız");
        }
    }//GEN-LAST:event_s_silActionPerformed

    private void t_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_silActionPerformed
        // TODO add your handling code here:
        int select=JOptionPane.showConfirmDialog(rootPane, "Silmek istedğinizden emin misniz?", "Silme İşlemi", JOptionPane.YES_NO_OPTION);
        if(select == 0){
            DB db =new  DB();
            int status = db.allSiparisDelete();
            db.close();
            refreshSiparis();}
    }//GEN-LAST:event_t_silActionPerformed

    private void bsiparisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsiparisActionPerformed
        // TODO add your handling code here:
       
      
        DB db = new DB();
        tbl_siparis.setModel(db.siparisFilter());
        db.close();
            
        
        
    }//GEN-LAST:event_bsiparisActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        refreshSiparis();
        refreshMusteri();
    }//GEN-LAST:event_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Siparis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Siparis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Siparis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Siparis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Siparis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arama;
    private javax.swing.JButton bsiparis;
    private javax.swing.JButton duzenle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField madi;
    private javax.swing.JTextField msoyadi;
    private javax.swing.JButton refresh;
    private javax.swing.JButton s_sil;
    private javax.swing.JButton sil;
    private javax.swing.JButton t_sil;
    private javax.swing.JTable tbl_musteri;
    private javax.swing.JTable tbl_siparis;
    private javax.swing.JButton teslimedildi;
    private javax.swing.JButton ySipariş;
    private javax.swing.JButton yeniMüsteri;
    private javax.swing.JButton yolda;
    // End of variables declaration//GEN-END:variables
}
